name: your_tour_guide
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.2.1
  modal_progress_hud_nsn: ^0.5.1
  flutter_signin_button: ^2.0.0
  bordered_text: ^2.0.0
  cloud_firestore: ^5.1.8
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  persistent_bottom_nav_bar: ^6.2.1
  animated_bottom_navigation_bar: ^1.4.0
  get: ^4.7.2
  google_maps_flutter: ^2.12.2
  url_launcher: ^6.3.1
  full_screen_image_null_safe: ^2.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  photo_view: ^0.15.0
  flutter_svg: ^2.1.0
  rate: ^0.0.2
  flutter_rating_bar: ^4.0.1
  flutter_bloc: ^9.1.1
  animated_splash_screen: ^1.3.0
  intl: ^0.19.0
  arabic_numbers: ^1.0.0
  readmore: ^3.0.0
  internet_connection_checker: ^3.0.1
  provider: ^6.1.5
  restart_app: ^1.3.2
  google_sign_in: ^6.3.0
  social_login_buttons: ^1.0.7
  flutter_facebook_auth: ^7.1.2
  device_preview: ^1.2.0
  maps_launcher: ^3.0.0+1
  dartz: ^0.10.1
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true